import{useEffect,useState}from'react';import{createGame,guess,scan}from'./game/engine';import{dateKey}from'./game/daily';import{heatFor,heatLabel,HEATS}from'./game/heat';import{ratingFor,scoreFor}from'./game/scoring';import type{Game,Mode,Result}from'./game/types';import{defaults,load,record,save,type Data}from'./storage';
type Screen='home'|'game'|'result'|'stats'|'how'|'settings'|'custom';
const buzz=(on:boolean,p:number|number[])=>{if(on&&'vibrate'in navigator)navigator.vibrate(p)};
function HeatLegend(){return <div className="legend">{HEATS.map((h,i)=><span className={h} key={h}><b>{'▮'.repeat(i+1)}</b>{heatLabel[h]}</span>)}</div>}
function App(){const[data,setData]=useState<Data>(()=>load()),[screen,setScreen]=useState<Screen>(()=>load().active?'home':'home'),[game,setGame]=useState<Game|null>(()=>load().active),[result,setResult]=useState<Result|null>(null),[toast,setToast]=useState(''),[install,setInstall]=useState<any>(null),[update,setUpdate]=useState(false),[onboard,setOnboard]=useState(()=>!load().settings.onboarded);
 useEffect(()=>save({...data,active:game}),[data,game]);useEffect(()=>{const p=(e:Event)=>{e.preventDefault();setInstall(e)};addEventListener('beforeinstallprompt',p);addEventListener('nh-update',()=>setUpdate(true));return()=>removeEventListener('beforeinstallprompt',p)},[]);
 const start=(mode:Mode,size:number)=>{const actual=mode==='daily'&&data.stats.dailyHistory[dateKey()]?'daily-practice':mode;const g=createGame(actual,size,dateKey());setData(d=>({...d,stats:{...d.stats,games:d.stats.games+1}}));setGame(g);setResult(null);setScreen('game')};
 const complete=(g:Game)=>{const r:Result={...g,completedAt:Date.now(),score:scoreFor(g.size,g.guesses.length),date:g.mode.startsWith('daily')?dateKey():undefined};setData(d=>({...d,stats:record(d.stats,r,g.mode==='daily')}));setGame(null);setResult(r);setScreen('result');buzz(data.settings.haptics,[60,40,120])};
 const changeSettings=(p:Partial<Data['settings']>)=>setData(d=>({...d,settings:{...d.settings,...p}}));

 return <main>{toast&&<div className="toast" role="status">{toast}</div>}{update&&<div className="update">Update ready <button onClick={()=>location.reload()}>Refresh</button></div>}
 {onboard&&<div className="modal"><section><div className="brandmark">#<i>🔥</i></div><p className="eyebrow">WELCOME, HUNTER</p><h2>Find the hidden number.</h2><p>Scan the grid. Read the heat. Commit to a guess. You start with 3 scans, and every miss earns another.</p><HeatLegend/><button className="primary" onClick={()=>{setOnboard(false);changeSettings({onboarded:true})}}>Let’s hunt</button><button className="textbtn" onClick={()=>{setOnboard(false);changeSettings({onboarded:true})}}>Skip tutorial</button></section></div>}
 {screen==='home'&&<Home data={data} start={start} go={setScreen} game={game} install={install?async()=>{await install.prompt();setInstall(null)}:undefined}/>} 
 {screen==='custom'&&<Custom back={()=>setScreen('home')} start={n=>start('custom',n)}/>} 
 {screen==='game'&&game&&<GameView game={game} setGame={setGame} finish={complete} back={()=>setScreen('home')} haptics={data.settings.haptics} announce={setToast}/>} 
 {screen==='result'&&result&&<Results result={result} home={()=>setScreen('home')} again={()=>start(result.mode.startsWith('daily')?'daily-practice':result.mode,result.size)} toast={setToast}/>} 
 {screen==='stats'&&<Stats data={data} back={()=>setScreen('home')} reset={()=>{setData(d=>({...d,stats:structuredClone(defaults.stats)}));setToast('Statistics reset')}}/>}
 {screen==='how'&&<Page title="How to Play" back={()=>setScreen('home')}><ol className="steps"><li><b>There’s a secret</b><span>A number from 1 to the board maximum.</span></li><li><b>Scan the grid</b><span>Tap a tile to reveal a nearby cluster.</span></li><li><b>Read the heat</b><span>Hotter tiles are numerically closer—not spatially closer.</span></li><li><b>Make your guess</b><span>Wrong guesses earn +1 scan. No higher/lower hints.</span></li><li><b>Win efficiently</b><span>Submit the exact number. Fewer guesses means a better rating.</span></li></ol><HeatLegend/></Page>}
 {screen==='settings'&&<Page title="Settings" back={()=>setScreen('home')}><Toggle label="Haptics" sub="Tactile feedback for scans and guesses" value={data.settings.haptics} set={v=>changeSettings({haptics:v})}/><Toggle label="Sound effects" sub="Subtle game audio (coming soon)" value={data.settings.sound} set={v=>changeSettings({sound:v})}/><p className="muted">Number Hunt stores games and settings only on this device.</p></Page>}</main>}
function Home({data,start,go,game,install}:{data:Data;start:(m:Mode,n:number)=>void;go:(s:Screen)=>void;game:Game|null;install?:()=>void}){const done=!!data.stats.dailyHistory[dateKey()];return <div className="home screen"><header><div className="logo"><div className="brandmark">#<i>🔥</i></div><div><p>NUMBER</p><h1>HUNT</h1></div></div><button className="iconbtn" onClick={()=>go('settings')} aria-label="Settings">⚙</button></header><section className="hero"><p className="eyebrow">READ THE HEAT · FIND THE NUMBER</p><h2>How sharp is your number sense?</h2></section>{game&&<button className="continue" onClick={()=>go('game')}><span>GAME IN PROGRESS</span><b>Continue {game.size}-tile hunt →</b></button>}<section className="play"><div className="sectionhead"><h3>Quick Play</h3><span>Choose your hunt</span></div><div className="presets">{[[25,'Easy'],[49,'Medium'],[81,'Hard'],[100,'Expert']].map(([n,l])=><button onClick={()=>start('quick',n as number)} key={n}><strong>{n}</strong><span>{l}</span></button>)}</div></section><button className="daily" onClick={()=>start('daily',100)}><span><small>DAILY HUNT · {dateKey()}</small><b>{done?'Completed — Practice again':'Today’s 100-tile challenge'}</b></span><em>{done?'✓':'🔥'}</em></button><div className="menu"><button onClick={()=>go('custom')}>⌗ <span><b>Custom Game</b><small>9–144 tiles</small></span></button><button onClick={()=>go('stats')}>▥ <span><b>Statistics</b><small>{data.stats.completed} hunts</small></span></button><button onClick={()=>go('how')}>? <span><b>How to Play</b><small>Learn in 20 seconds</small></span></button>{install&&<button onClick={install}>↓ <span><b>Install Number Hunt</b><small>Play offline</small></span></button>}</div></div>}
function GameView({game,setGame,finish,back,haptics,announce}:{game:Game;setGame:(g:Game)=>void;finish:(g:Game)=>void;back:()=>void;haptics:boolean;announce:(s:string)=>void}){const[input,setInput]=useState(''),[error,setError]=useState('');const cols=Math.ceil(Math.sqrt(game.size));const submit=()=>{const out=guess(game,Number(input));if(out.status==='invalid'){setError(`Enter a whole number from 1 to ${game.size}`);return}if(out.status==='duplicate'){setError('You already guessed that number.');return}setInput('');setError('');if(out.status==='correct')finish(out.game);else{setGame(out.game);announce('Not the target. You earned one scan.');setTimeout(()=>announce(''),1800);buzz(haptics,[35,35,35])}};return <div className="game screen"><header><button className="iconbtn" onClick={back} aria-label="Leave game">‹</button><div><small>{game.mode.replace('-',' ').toUpperCase()}</small><b>1–{game.size}</b></div><div className="scanpill">◉ <b>{game.scans}</b> scans</div></header><div className="gameinfo"><span><b>{game.guesses.length}</b> guesses</span><span>Tap a neutral tile to scan</span></div><div className="grid" style={{'--cols':cols} as React.CSSProperties}>{Array.from({length:game.size},(_,i)=>i+1).map(n=>{const revealed=game.revealed.includes(n),heat=revealed?heatFor(n,game.secret,game.size):'';return <button key={n} aria-label={`Number ${n}${revealed?`, ${heatLabel[heat as keyof typeof heatLabel]}`:', unrevealed'}`} className={`tile ${heat}`} disabled={revealed||game.scans<1} onClick={()=>{const next=scan(game,n);setGame(next);buzz(haptics,18)}}><b>{n}</b>{revealed&&<i>{'▮'.repeat(HEATS.indexOf(heat as any)+1)}</i>}</button>})}</div><div className="guessbar"><div className="history">{game.guesses.length?<>{game.guesses.map(n=><span key={n}>× {n}</span>)}</>:<small>Make every guess count.</small>}</div><form onSubmit={e=>{e.preventDefault();submit()}}><label htmlFor="guess">Your guess</label><input id="guess" inputMode="numeric" pattern="[0-9]*" value={input} onChange={e=>setInput(e.target.value)} placeholder={`1–${game.size}`} aria-describedby="guess-error"/><button className="primary">Guess</button></form><div id="guess-error" className="error" role="alert">{error}</div></div></div>}
function Results({result,home,again,toast}:{result:Result;home:()=>void;again:()=>void;toast:(s:string)=>void}){const [shown,setShown]=useState(0);useEffect(()=>{if(matchMedia('(prefers-reduced-motion: reduce)').matches){setShown(result.score);return}let id=0;const start=performance.now();const tick=(t:number)=>{setShown(Math.round(result.score*Math.min(1,(t-start)/700)));if(t-start<700)id=requestAnimationFrame(tick)};id=requestAnimationFrame(tick);return()=>cancelAnimationFrame(id)},[result.score]);const text=`NUMBER HUNT ${result.date?'#'+result.date:'🔥'}\n\n🎯 ${result.guesses.length} guesses\n🔢 ${result.size} numbers\n🏆 ${result.score.toLocaleString()} points\n\n🟦🟨🟧🔥`;const share=async()=>{try{if(navigator.share)await navigator.share({title:'Number Hunt',text});else{await navigator.clipboard.writeText(text);toast('Result copied!')}}catch{/* user cancelled */}};return <div className="result screen"><div className="confetti" aria-hidden>✦ • ✧ • ✦</div><p className="eyebrow">HUNT COMPLETE</p><h1>{ratingFor(result.guesses.length)}</h1><p>You found <b>{result.secret}</b> in</p><div className="heroStat"><strong>{result.guesses.length}</strong><span>GUESSES</span></div><div className="score">{shown.toLocaleString()} <small>POINTS</small></div><div className="resultgrid"><span><small>BOARD</small><b>{result.size} tiles</b></span><span><small>SCANS</small><b>{result.scansUsed} used</b></span><span><small>TIME</small><b>{formatTime(result.completedAt-result.startedAt)}</b></span><span><small>MODE</small><b>{result.mode.replace('-',' ')}</b></span></div><div className="guesslist"><small>YOUR GUESSES</small><p>{result.guesses.map((n,i)=><span className={i===result.guesses.length-1?'win':''} key={n}>{n}</span>)}</p></div><button className="primary" onClick={share}>Share Result</button><button onClick={again}>Play Again</button><button className="textbtn" onClick={home}>Back to Home</button></div>}
const formatTime=(ms:number)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
function Stats({data,back,reset}:{data:Data;back:()=>void;reset:()=>void}){const s=data.stats,max=Math.max(1,...Object.values(s.distribution));return <Page title="Statistics" back={back}><div className="statgrid"><span><b>{s.completed}</b><small>Games</small></span><span><b>{s.completed?(s.totalGuesses/s.completed).toFixed(1):'—'}</b><small>Avg guesses</small></span><span><b>{s.bestScore.toLocaleString()}</b><small>Best score</small></span><span><b>{s.dailyStreak}</b><small>Daily streak</small></span></div><h3>Guess distribution</h3><div className="bars">{['1','2','3','4','5','6','7','8','9'].map(k=><div key={k}><b>{k==='9'?'9+':k}</b><i style={{width:`${Math.max(3,(s.distribution[k]||0)/max*100)}%`}}/><span>{s.distribution[k]||0}</span></div>)}</div><h3>Difficulty records</h3>{[25,49,81,100].map(n=><div className="record" key={n}><b>{n} tiles</b><span>{s.bySize[n]?.games||0} games · Best {(s.bySize[n]?.best||0).toLocaleString()}</span></div>)}<button className="danger" onClick={()=>confirm('Reset all statistics? This cannot be undone.')&&reset()}>Reset Statistics</button></Page>}
function Custom({back,start}:{back:()=>void;start:(n:number)=>void}){const[n,setN]=useState(64);return <Page title="Custom Hunt" back={back}><div className="custom"><p>Build a board between 9 and 144 tiles.</p><strong>{n}</strong><input aria-label="Board size" type="range" min="9" max="144" value={n} onChange={e=>setN(Math.max(9,Math.min(144,+e.target.value)))}/><input aria-label="Exact board size" type="number" min="9" max="144" value={n} onChange={e=>setN(Math.max(9,Math.min(144,+e.target.value||9)))}/><button className="primary" onClick={()=>start(n)}>Start {n}-tile Hunt</button></div></Page>}
function Page({title,back,children}:{title:string;back:()=>void;children:React.ReactNode}){return <div className="page screen"><header><button className="iconbtn" onClick={back}>←</button><h1>{title}</h1></header>{children}</div>}
function Toggle({label,sub,value,set}:{label:string;sub:string;value:boolean;set:(v:boolean)=>void}){return <label className="toggle"><span><b>{label}</b><small>{sub}</small></span><input type="checkbox" checked={value} onChange={e=>set(e.target.checked)}/></label>}
export default App;
